services:
  database:
    image: mysql:latest
    restart: always
    expose:   
      - "3306"
    environment:
      MYSQL_DATABASE: Oldies
      MYSQL_USER: Ratchaphon1412
      MYSQL_PASSWORD: Nueng1412
      MYSQL_ROOT_PASSWORD: Nueng1412
    volumes:
      - ./database:/var/lib/mysql
      - ./database_temp:/var/run/mysqld
    networks:
      - backend_service
  backend:
    container_name: backend-oldies
    command: >
      sh -c "poetry run python3 manage.py wait_db &&
              poetry run python3 manage.py makemigrations Users Products &&
             poetry run python3 manage.py migrate &&
             poetry run gunicorn --bind 0.0.0.0:8000 Oldies.wsgi:application --daemon"
    env_file: .env
    build: 
      context: .
      dockerfile: dockerfile
    tty: true
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      database:
        condition: service_started
      
    networks:
      - backend_service
    
  webserver:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - backend_service
    depends_on:
      - backend
  
  databaseweb:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    expose:
      - "80"
    networks:
      - backend_service


networks:
  backend_service:
  